{"@timestamp":"2024-12-29T02:21:14.497Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T02:21:14.628Z","caller":"sqlx/utils.go:142","content":"Error on getting sql instance of tcp(172.17.0.2:3306)/mall_user?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai: dial tcp 172.17.0.2:3306: connect: no route to host","level":"error","span":"0c7eaec975fbda0c","trace":"e9a32cf759c7b3a8cc29bcd4adfb44f1"}
{"@timestamp":"2024-12-29T02:21:14.628Z","caller":"sqlx/utils.go:142","content":"Error on getting sql instance of tcp(172.17.0.2:3306)/mall_user?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai: dial tcp 172.17.0.2:3306: connect: no route to host","level":"error","span":"b958dca9c4ccc518","trace":"477d042e8f5c1782eaf7add42c21cfe8"}
{"@timestamp":"2024-12-29T02:21:19.498Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T02:23:48.132Z","caller":"sqlx/utils.go:142","content":"Error on getting sql instance of tcp(172.17.0.2:3306)/mall_user?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai: dial tcp 172.17.0.2:3306: connect: no route to host","level":"error","span":"47de57b70c944c5a","trace":"72e17c4bd270f9c1f60d28397c7f4b30"}
{"@timestamp":"2024-12-29T02:23:49.516Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T02:24:34.520Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T02:35:39.612Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T02:38:14.629Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T02:41:12.018Z","caller":"sqlx/utils.go:147","content":"stmt: insert into `wallet_transactions` (`user_id`,`order_id`,`amount`,`type`,`status`,`remark`) values (2, '', 100, 1, 1, {新用户注册奖励 true}), error: Error 1062 (23000): Duplicate entry '' for key 'wallet_transactions.idx_order_id'","level":"error","span":"7eb96bf14e40ff7e","trace":"6580474bdd0e3aa745d54f334292e0ad"}
{"@timestamp":"2024-12-29T02:41:14.649Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T02:41:22.849Z","caller":"sqlx/utils.go:147","content":"stmt: insert into `wallet_transactions` (`user_id`,`order_id`,`amount`,`type`,`status`,`remark`) values (3, '', 100, 1, 1, {新用户注册奖励 true}), error: Error 1062 (23000): Duplicate entry '' for key 'wallet_transactions.idx_order_id'","level":"error","span":"548ddde475b97af0","trace":"c4d36b7c165d73e485be34d89b8493b8"}
{"@timestamp":"2024-12-29T02:41:24.650Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T02:44:23.540Z","caller":"sqlx/utils.go:147","content":"stmt: insert into `wallet_transactions` (`user_id`,`order_id`,`amount`,`type`,`status`,`remark`) values (4, '', 100, 1, 1, {新用户注册奖励 true}), error: Error 1062 (23000): Duplicate entry '' for key 'wallet_transactions.idx_order_id'","level":"error","span":"d76ed5cc68ab1df7","trace":"ffe34a253dfc593415eea57183bfeb04"}
{"@timestamp":"2024-12-29T02:44:25.683Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T02:57:59.532Z","caller":"sqlx/utils.go:147","content":"stmt: insert into `wallet_transactions` (`user_id`,`order_id`,`amount`,`type`,`status`,`remark`) values (5, '', 100, 1, 1, {新用户注册奖励 true}), error: Error 1062 (23000): Duplicate entry '' for key 'wallet_transactions.idx_order_id'","level":"error","span":"18940496cb5cd9c7","trace":"7698e33db8a004dfbc14253f292ebcee"}
{"@timestamp":"2024-12-29T02:58:00.784Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T02:59:32.879Z","caller":"sqlx/utils.go:147","content":"stmt: insert into `wallet_transactions` (`user_id`,`order_id`,`amount`,`type`,`status`,`remark`) values (6, '', 100, 1, 1, {新用户注册奖励 true}), error: Error 1062 (23000): Duplicate entry '' for key 'wallet_transactions.idx_order_id'","level":"error","span":"fb3c1d8f9aad824a","trace":"2ca0f731f8972db7fab9cf594111ce27"}
{"@timestamp":"2024-12-29T02:59:34.385Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T02:59:42.788Z","caller":"sqlx/utils.go:147","content":"stmt: insert into `wallet_transactions` (`user_id`,`order_id`,`amount`,`type`,`status`,`remark`) values (7, '', 100, 1, 1, {新用户注册奖励 true}), error: Error 1062 (23000): Duplicate entry '' for key 'wallet_transactions.idx_order_id'","level":"error","span":"24cab27dc9534c3c","trace":"f1d09e409499dea603be222b3324e545"}
{"@timestamp":"2024-12-29T02:59:44.386Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T03:05:39.697Z","caller":"sqlx/utils.go:147","content":"stmt: insert into `wallet_transactions` (`user_id`,`order_id`,`amount`,`type`,`status`,`remark`) values (8, '', 100, 1, 1, {新用户注册奖励 true}), error: Error 1062 (23000): Duplicate entry '' for key 'wallet_transactions.idx_order_id'","level":"error","span":"a13439cf94f3f6a3","trace":"52ab4e0b1837b341a3dc9d6c4b39e391"}
{"@timestamp":"2024-12-29T03:05:39.697Z","caller":"logic/registerlogic.go:105","content":"init points failed: Error 1062 (23000): Duplicate entry '' for key 'wallet_transactions.idx_order_id'","level":"error"}
{"@timestamp":"2024-12-29T03:05:39.812Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T03:07:35.287Z","caller":"sqlx/utils.go:147","content":"stmt: insert into `wallet_transactions` (`user_id`,`order_id`,`amount`,`type`,`status`,`remark`) values (9, '', 100, 1, 1, {新用户注册奖励 true}), error: Error 1062 (23000): Duplicate entry '' for key 'wallet_transactions.idx_order_id'","level":"error","span":"c10a3992fee9ddeb","trace":"fae5b4e0184ad63e5ef571b4897018ab"}
{"@timestamp":"2024-12-29T03:07:39.846Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T03:11:18.080Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T03:11:58.084Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T03:12:03.084Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T03:12:07.226Z","caller":"sqlx/utils.go:147","content":"stmt: insert into `users` (`username`,`password`,`phone`,`email`,`nickname`,`avatar`,`gender`,`member_level`,`status`) values ('testuser', 'abd70780a1265332c1ecebdfd351020ccfc77e51f6b66d74f266343356da8669', {13800138000 true}, {test@example.com true}, { false}, { false}, '', 0, 1), error: Error 1062 (23000): Duplicate entry 'testuser' for key 'users.idx_username'","level":"error","span":"10a2a445b9a83d11","trace":"fe0251695ce38f82bbb4e017bb9a090e"}
{"@timestamp":"2024-12-29T03:12:08.085Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T03:18:08.332Z","caller":"sqlx/utils.go:147","content":"stmt: insert into `users` (`username`,`password`,`phone`,`email`,`nickname`,`avatar`,`gender`,`member_level`,`status`) values ('testuser', 'abd70780a1265332c1ecebdfd351020ccfc77e51f6b66d74f266343356da8669', {13800138000 true}, {test@example.com true}, { false}, { false}, '', 0, 1), error: Error 1062 (23000): Duplicate entry 'testuser' for key 'users.idx_username'","level":"error","span":"270eff0ebb30e766","trace":"776fc1f71376eb53ac6c45a4fa4c169d"}
{"@timestamp":"2024-12-29T03:18:08.332Z","caller":"logic/registerlogic.go:88","content":"Failed to insert user: Error 1062 (23000): Duplicate entry 'testuser' for key 'users.idx_username'","level":"error","span":"6d6def688160e34c","trace":"776fc1f71376eb53ac6c45a4fa4c169d"}
{"@timestamp":"2024-12-29T03:18:08.333Z","caller":"logic/registerlogic.go:144","content":"Transaction failed: Error 1062 (23000): Duplicate entry 'testuser' for key 'users.idx_username'","level":"error","span":"6d6def688160e34c","trace":"776fc1f71376eb53ac6c45a4fa4c169d"}
{"@timestamp":"2024-12-29T03:18:10.683Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T03:24:47.092Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T03:25:07.094Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T03:31:10.600Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T03:42:45.675Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T03:52:19.757Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T04:58:59.881Z","caller":"sqlx/utils.go:142","content":"Error on getting sql instance of tcp(172.17.0.2:3306)/mall_user?parstTime=true&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci: Error 1193 (HY000): Unknown system variable 'parstTime'","level":"error","span":"cb7aeee0b99d7056","trace":"bd546e6c2df700fd615393e012bc85d8"}
{"@timestamp":"2024-12-29T04:58:59.882Z","caller":"sqlx/utils.go:142","content":"Error on getting sql instance of tcp(172.17.0.2:3306)/mall_user?parstTime=true&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci: Error 1193 (HY000): Unknown system variable 'parstTime'","level":"error","span":"58c46e9ac88a8af4","trace":"bd546e6c2df700fd615393e012bc85d8"}
{"@timestamp":"2024-12-29T04:58:59.883Z","caller":"sqlx/utils.go:142","content":"Error on getting sql instance of tcp(172.17.0.2:3306)/mall_user?parstTime=true&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci: Error 1193 (HY000): Unknown system variable 'parstTime'","level":"error","span":"83aa1630863bb60c","trace":"bd546e6c2df700fd615393e012bc85d8"}
{"@timestamp":"2024-12-29T04:58:59.884Z","caller":"sqlx/utils.go:142","content":"Error on getting sql instance of tcp(172.17.0.2:3306)/mall_user?parstTime=true&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci: Error 1193 (HY000): Unknown system variable 'parstTime'","level":"error","span":"3ec8b9a054e31e76","trace":"bd546e6c2df700fd615393e012bc85d8"}
{"@timestamp":"2024-12-29T04:59:01.852Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T05:00:42.390Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T05:00:57.392Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T05:16:35.063Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T05:18:30.075Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T05:21:42.901Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T05:27:12.939Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T10:19:05.463Z","caller":"sqlx/utils.go:142","content":"Error on getting sql instance of tcp(172.17.0.2:3306)/mall_user?parseTime=true&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci: dial tcp 172.17.0.2:3306: connect: no route to host","level":"error","span":"7cd02dd1341b0ad9","trace":"e0156df7898ce5d67dc5a6b2c7eb1e4b"}
{"@timestamp":"2024-12-29T10:19:05.463Z","caller":"sqlx/utils.go:142","content":"Error on getting sql instance of tcp(172.17.0.2:3306)/mall_user?parseTime=true&loc=Local&charset=utf8mb4&collation=utf8mb4_unicode_ci: dial tcp 172.17.0.2:3306: connect: no route to host","level":"error","span":"f116d1b2ee9ffef2","trace":"dbc0668ee2a5b11c268bd6784fd6ef72"}
{"@timestamp":"2024-12-29T10:19:07.029Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
{"@timestamp":"2024-12-29T10:21:41.043Z","caller":"trace/agent.go:148","content":"[otel] error: Post \"http://127.0.0.1:14268/api/traces\": dial tcp 127.0.0.1:14268: connect: connection refused","level":"error"}
